### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by snax4a** [snax4a/async-repository#1]
@bhamer
First I would like to thank you for your time spent on your async-repository project description 
I really like your implementation but Im not sure how should I update entity from my service.
Could you provide a small example of how can I update Entity with this UoW and Repository patterns?

**Comment by bhamer** [comment]
@snax4a 
Appreciate the feedback. I have an updated example and response ready, but have a favor to ask - I just enabled the Discussions feature on the repo so would you mind copying this over as a new discussion so it's there for reference?

**Comment by snax4a** [comment]
Of course, will do it in few minutes

W dniu czw., 29.04.2021 o 22:41 Brandon ***@***.***>
napisał(a):
